# Use the official .NET image as a build stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["VideoGameApi/VideoGameApi.csproj", "VideoGameApi/"]
RUN dotnet restore "VideoGameApi/VideoGameApi.csproj"
COPY . .
WORKDIR "/src/VideoGameApi"
RUN dotnet build "VideoGameApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "VideoGameApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VideoGameApi.dll"]
