// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameApi.Data;

#nullable disable

namespace VideoGameApi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20250811235312_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameApi.Models.VideoGame", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = "2",
                            Developer = "Santa Monica Studio",
                            Platform = "PlayStation 4",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = "3",
                            Developer = "343 Industries",
                            Platform = "Xbox Series X/S",
                            Publisher = "Xbox Game Studios",
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = "4",
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = "5",
                            Developer = "CD Projekt Red",
                            Platform = "PC, PlayStation 4, Xbox One, Nintendo Switch",
                            Publisher = "CD Projekt",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = "6",
                            Developer = "Square Enix",
                            Platform = "PlayStation 4",
                            Publisher = "Square Enix",
                            Title = "Final Fantasy VII Remake"
                        },
                        new
                        {
                            Id = "7",
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Animal Crossing: New Horizons"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
